### ISSUE TITLE
question pihole and ios

### ISSUE THREAD

**Issue by leeuwtjex** [upal212/pihole-ios-update-blocklist#1]
Hi Upal212,

There is no real issue, only a question, but there wasn't any other way to contact you.
I have seen your pihole ios blocklist at github.
When I open it I see only a couple of domain on it.
Searching on pihole blocklists for ios doesn't give much result. 
What is it with ios and pihole. Why isn't there more attention for it.
Is there anything different for ios compared to the ads for android?

Thanks for any information. I will try your list and see.

Dirk.

**Comment by upal212** [comment]
Hello Leeuwtjex,

Thank you for reaching out.
This blocklist actually points to the hostname(s) of the iOS update servers which sometimes automatically update the device for you overnight which eventually leads to losing an iOS version/jailbreak that you cannot downgrade back to in the later option as Apple stops signing older versions.

Hence, this list blocks all the update servers that iOS connects with - which eventually lands up telling an user that it could not connect to the 'iOS Update Servers' which does not lead to ending up with a new iOS version if left out overnight.

**For Android there must be other hostname(s) to stop the automatic updates (if you have any) depending on the manufacturer of your device or phone. 

Regards,
Upal
